---
- name: Install java in Amazon linux
  ansible.builtin.yum:
    name: java-1.8.0-amazon-corretto-devel
    state: present
  when: ansible_os_family == 'RedHat'
- name: Install java in Ubuntu linux
  ansible.builtin.apt:
    name: openjdk-8-jdk
    state: present
  when: ansible_os_family == 'Debian'
- name: Download SonarQube
  ansible.builtin.get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.1.zip
    dest: /opt/
    mode: "0644"
- name: Extract SonarQube
  ansible.builtin.unarchive:
    src: /opt/sonarqube-7.9.1.zip
    dest: /opt/
    remote_src: true
    creates: /opt/sonarqube-7.9.1
- name: Rename SonarQube directory
  ansible.builtin.command: mv /opt/sonarqube-7.9.1 /opt/sonarqube
  args:
    creates: /opt/sonarqube
- name: Set up SonarQube as a service
  ansible.builtin.template:
    src: sonarqube.service.j2
    dest: /etc/systemd/system/sonarqube.service
    mode: '0777'
  notify: Restart sonarqube
