---
- name: Install java in Amazon linux
  ansible.builtin.yum:
    name: java-1.8.0-amazon-corretto-devel
    state: present
  when: ansible_os_family == 'RedHat'
- name: Install java in Ubuntu linux
  ansible.builtin.apt:
    name: openjdk-8-jdk
    state: present
  when: ansible_os_family == 'Debian'
- name: Download Nexus
  ansible.builtin.get_url:
    url: https://download.sonatype.com/nexus/3/nexus-3.66.0-02-unix.tar.gz
    dest: /opt/
    mode: "0644"
- name: Extract Nexus
  ansible.builtin.unarchive:
    src: /opt/nexus-3.66.0-02-unix.tar.gz
    dest: /opt/
    remote_src: true
    creates: /opt/nexus-3.66.0-02
- name: Rename Nexus
  ansible.builtin.command: mv /opt/nexus-3.66.0-02 /opt/nexus
  args:
    creates: /opt/nexus
- name: Add nexus user
  ansible.builtin.user:
    name: nexus
    comment: Nexus Repository Manager
    shell: /sbin/nologin
    create_home: false
- name: Change ownership of Nexus directory
  ansible.builtin.file:
    path: /opt/nexus
    owner: nexus
    group: nexus
    recurse: true
- name: Change ownership of sonatype-work
  ansible.builtin.file:
    path: /opt/sonatype-work
    owner: nexus
    group: nexus
    recurse: true
- name: Configure Nexus service
  ansible.builtin.template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service
    mode: '0777'
- name: Start Nexus service
  ansible.builtin.service:
    name: nexus
    state: started
    enabled: true
